[package]
name = "noserc"
version = "0.1.0"
authors = ["Erlend Tobiassen <erlentob@stud.ntnu.no>"]

[lib]
name = "noserc"
path = "src/noserc.rs"

[dependencies]
nom = "4.0.0"
codegen = { git = "https://github.com/carllerche/codegen" }