[package]
name = "retreat-server"
version = "0.1.0"
authors = ["Erlend Tobiassen <erlentob@stud.ntnu.no>"]

[[bin]]
name = "retreat-server"
path = "src/server.rs"

[dependencies]
mio = "0.6.14"
retreat-shared = {path = "../retreat-shared", version = "0.1.0"}