[package]
name = "retreat-shared"
version = "0.1.0"
authors = ["Erlend Tobiassen <erlentob@stud.ntnu.no>"]

[lib]
name = "rlib"
path = "src/game.rs"

[dependencies]
noser = { path = "../noser" }

[build-dependencies]
noserc = { path = "../noserc" }